use_frameworks!

platform :ios, '8.0'

target 'TDWebViewSwipeBack_Example' do
  pod 'TDWebViewSwipeBack', :path => '../'

  target 'TDWebViewSwipeBack_Tests' do
    inherit! :search_paths

    
  end
end
